### ISSUE TITLE
Possible division-by-zero

### ISSUE THREAD

**Issue by issuefiler** [ianprime0509/pitchy#1]
# The 𝒎ₜ′(𝜏)

![𝒎ₜ′(𝜏)](https://user-images.githubusercontent.com/57908781/81255724-66453980-9069-11ea-80ef-045fc2f95a3d.png)

## <sub>Here you’re assuming</sub> **𝒎ₜ′(𝜏)≠0 for any valid 𝜏 if 𝒎ₜ′(0)≠0**<sub>.</sub>

The line #332.

https://github.com/ianprime0509/pitchy/blob/6af63bc2718ad187c176c62dce46a711acdd1879/src/index.ts#L319-L335

Can you be sure about that? The next 𝒎ₜ′ function value **after subtraction** might be zero even though the first value is not zero.

## A counterexample 1

Given a sampled window 𝒙＝[ 0 1 1 0 ] and 𝑡＝0,
- 𝒎ₜ′(0)＝4
- 𝒎ₜ′(1)＝4
- 𝒎ₜ′(2)＝2
- 𝒎ₜ′(3)＝0
in which case it divides by zero.

## A counterexample 2

Given a sampled window 𝒙＝[ 0 0 1 1 0 0 ] and 𝑡＝0,
- 𝒎ₜ′(0)＝4
- 𝒎ₜ′(1)＝4
- 𝒎ₜ′(2)＝4
- 𝒎ₜ′(3)＝2
- 𝒎ₜ′(4)＝0
- 𝒎ₜ′(5)＝0
in which case it divides by zero.

## Note 1

 As 𝒎ₜ′(𝜏－1)≥𝒎ₜ′(𝜏), if you’ve encountered a zero, the subsequent function values are also zero. I. e. you can break the loop at that point and zero out the following NSDF values.

## Note 2

 Because 𝒎ₜ′(𝜏)≥0, when you check whether the value after subtraction is zero, you can check for whether the value **is 0 _or negative_** instead, taking floating-point errors into account.

**Comment by ianprime0509** [comment]
Thanks for pointing this out and for your suggestions on how to improve the behavior! I addressed this in b68ee73840ed05bd4cb51645ed91a6edd4f796ba.
