### ISSUE TITLE
using pitchy with jest v28

### ISSUE THREAD

**Issue by glend1** [ianprime0509/pitchy#110]
I have created a [question on stackoverflow](https://stackoverflow.com/questions/73151763/upgrading-from-jest-v27-to-v28-causes-an-import-error-for-pitchy) detailing my problem. 

But the short version is that this library doesn't work when importing using `jest` v28. I have fixed this by changing the `package.json` from this library

From;

````
...
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./index.d.ts",
      "import": "./index.js"
    }
  },
...
````

To;

````
...
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "default": "./index.js"
    }
  },
...
````

I wasn't able to find any documentation about what `exports` is supposed to do but this style seems more inline with other packages i've looked at.

**Comment by ianprime0509** [comment]
Thank you for pointing this out! I merged #112 which you opened, and it'll be included in the automated next release.
