### ISSUE TITLE
Option to take volume into consideration

### ISSUE THREAD

**Issue by bali182** [ianprime0509/pitchy#188]
Hello, first of all thanks for the lib, it's pretty intuitive to use!

I was wondering if it would possible to somehow take volume into consideration. For now I'm just trying to make an example that prints the note name from a guitar played through an audio interface. It works well, but sometimes when nothing is played, some notes are still picked up, (even though I only print the note detected, if the accuracy number is above 0.8).

I didn't really check the audio APIs in much detail, but would it be possible to somehow put a limit on the minimum volume needed to detect as a pitch? Eg.:

```ts
const [measuredFrequency, accuracy] = detector.findPitch(
    input, 
    sampleRate, 
    -15 /* stuff below -15 db would come back with 0 accuracy or something */
)
```

I hope it makes sense

**Comment by ianprime0509** [comment]
Thanks for the suggestion! I think that would be a good feature to have. I'll take a look and investigate the best way to implement this.
