### ISSUE TITLE
Typo: “NSDF,” not “NDSF.”

### ISSUE THREAD

**Issue by issuefiler** [ianprime0509/pitchy#2]
The _normalized square difference function_, also named the _SNAC_ (_special normalization of the autocorrelation_) function in [his succeeding work in 2008](http://www.cs.otago.ac.nz/research/publications/oucs-2008-03.pdf).

https://github.com/ianprime0509/pitchy/blob/6af63bc2718ad187c176c62dce46a711acdd1879/src/index.ts#L209-L337

**Comment by ianprime0509** [comment]
Thank you for pointing this out! I fixed the typos in 2c4287659b5bb27d7f8742dce6f1090d1c6ad9bf.
