### ISSUE TITLE
Update README to contain a direct import

### ISSUE THREAD

**Issue by ArcherScript** [ianprime0509/pitchy#201]
I got a little bit confused using this tool because I was trying to figure out why an `async` import was required.

I realize that this is how you're supposed to do commonJS imports, but I think that it would be nice to see a regular import in the documentation as well. This will help other users not be as thrown off when importing the package.

I don't mind submitting a PR, I was thinking updating the readme to read something like below:

```
To import this package directly you can just import it as normal:
import { PitchDetector } from "pitchy"
Or from the cdn
...
```

**Comment by ianprime0509** [comment]
Thanks for the suggestion! I agree this is a good thing to document; it doesn't make much sense to provide a code example of using the library from a CDN but not as an installed package, which is how most users will likely be using it. I opened #203 to fix this and make a few more tweaks to the README.
