### ISSUE TITLE
Failing on analyserNode.getFloatTimeDomainData(input)

### ISSUE THREAD

**Issue by htmljosh** [ianprime0509/pitchy#6]
Using your example

In firefox I get 
"Uncaught TypeError: AnalyserNode.getFloatTimeDomainData: Argument 1 is not an object."

In chrome I get 
"Uncaught TypeError: Failed to execute 'getFloatTimeDomainData' on 'AnalyserNode': parameter 1 is not of type 'Float32Array'."

Running on Ubuntu 20.04 at sample rate 48000, hoping you could give a quick tip!

**Comment by ianprime0509** [comment]
Hello! I added a runnable version of the README example here: https://github.com/ianprime0509/pitchy/blob/e8e94102ea0654484e7092aa3be85500b65aaa4d/examples/simple/index.html If that doesn't work for you, please let me know; it may help you debug the issue you're facing in your code.

As for the error you're getting, the argument to the `getFloatTimeDomainData` method must be a `Float32Array`: https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatTimeDomainData You should create such an array using `new Float32Array(detector.inputLength)` (where `detector` is `PitchDetector.forFloat32Array(analyserNode.fftSize)`) and then pass that to the `getFloatTimeDomainData` method. Your error indicates that you're passing something else to that method that isn't a `Float32Array`.

If that isn't working for some reason, please share the snippet of your code where that method is failing so I can try to identify what might be going on.

**Comment by htmljosh** [comment]
That example is working for me. Thank you! This is very cool.
